[versions]
activity-compose = "1.9.0"
agp = "8.4.1"
compose-bom = "2024.05.00"
compose-destinations = "1.10.2"
compose-plugin = "1.6.10"
core-ktx = "1.13.1"
core-splashscreen = "1.0.1"
hilt = "2.51.1"
hilt-navigation-compose = "1.2.0"
kotlin = "2.0.0-RC3"
kotlinx-serialization = "1.7.0-RC"
kotlinx-datetime = "0.6.0"
ksp = "2.0.0-RC3-1.0.20"
# https://issuetracker.google.com/issues/336842920
#noinspection GradleDependency
lifecycle-runtime = "2.8.0"
lifecycle-viewmodel = "2.8.0"
uuid = "0.8.4"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-destinations = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "compose-destinations" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "compose-destinations" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime" }
lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
uuid = { group = "com.benasher44", name = "uuid", version.ref = "uuid" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeJB = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
