name: Deploy website

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - uses: actions/setup-gradle@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: current
          cache: pnpm
      - uses: extractions/setup-just@v2
      - run: just build-web-ci
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy build/web/dist --project-name=sheng-ji
