name: Initialize project
on: push

jobs:
  initialize-project:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'android-app-template'
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run initialization script
        run: |
          kotlin scripts/initialize.main.kts -- "a" "$(gh repo view --json description -t "{{.description}}")" "$(gh repo view --json owner -t "{{.owner.login}}")"
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "feat: initialize repo"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
